### ISSUE TITLE
errors when trying to equip

### ISSUE THREAD

**Issue by ghost** [Gmod4phun/gasmask#1]

**Comment by Gmod4phun** [comment]
Works fine on my end. What gamemode, what addons are you using. Also posting the error would help with identifying the problem.

**Comment by ghost** [comment]
sandbox and TFA, Sharpeye, Life Mod, etc.

EDIT: disabling fixed it, but i don't know whats conflicting.

**Comment by ghost** [comment]
[ERROR] addons/gasmask-master/lua/autorun/server/g4p_gasmask_sv.lua:40: attempt to index a nil value
  1. unknown - addons/gasmask-master/lua/autorun/server/g4p_gasmask_sv.lua:40
   2. unknown - lua/includes/modules/concommand.lua:54

**Comment by Gmod4phun** [comment]
I tried it with TFA weapons enabled and it worked fine. A problem can be caused by an addon possibly overriding the Give() function, which is a fault of said addon. You would have to keep enabling them one by one to see when it starts to throw out errors. If you can find the time to do that, let me know.

**Comment by ghost** [comment]
hm, give function. I do have an addon that adds manual picking up of weapons. i'll disable that and get back to you.

**Comment by ghost** [comment]
aaand it was Manual Pickup. 

thanks for the help :)
